Avonale_Web/Avonale_Web/Models/Repositorio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Avonale_Web.Models
{
    /// <summary>
    /// Classe para deserializar o objeto em Json
    /// </summary>
    public class Repositorio
    {
        /// <summary>
        /// Nome do repositório
        /// </summary>
        public string name { get; set; }

        /// <summary>
        /// Descrição do repositório
        /// </summary>
        public string description { get; set; }

        /// <summary>
        /// Linguagem do repositório
        /// </summary>
        public string language { get; set; }

        /// <summary>
        /// Ultima data de atualização
        /// </summary>
        public DateTime updated_at { get; set; }

        /// <summary>
        /// Dono do repositório
        /// </summary>
        public Owner owner { get; set; }

        public bool favorito { get; set; }

    }

    /// <summary>
    /// Classe suporte para deserializar o objeto em Json
    /// </summary>
    public class Owner
    {
        public string login { get; set; }
    }
}

Avonale_Web/Avonale_Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Avonale_Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View(GitRepositorios.repositoriosGit);

        }

    }
}

Avonale_Web/Avonale_Web/Controllers/RepositoriosController.cs
using Avonale_Web.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Avonale_Web.Controllers
{
    public class RepositoriosController : Controller
    {
        /// <summary>
        /// Retorna todos os repositórios
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(GitRepositorios.TodosRepositorios());

        }
        
        /// <summary>
        /// Seção de buscar repositório pelo nome exato ou nome parcial
        /// </summary>
        /// <param name="filtro"> Palavra para ser filtrada </param>
        /// <param name="opcao"> True para filtro exato ou false para filtro parcial </param>
        /// <returns></returns>
        public ActionResult Buscar(string filtro, bool? opcao)
        {
            if (filtro == null)
            {
                return View(GitRepositorios.TodosRepositorios());
            }
            if (opcao == true)
            {
                return View(GitRepositorios.TodosRepositorios().Where(a => a.name == filtro).ToList());
            }
            else
            {
                return View(GitRepositorios.TodosRepositorios().Where(a => a.name.ToUpper().Contains(filtro.ToUpper())).ToList());
            }

        }

        /// <summary>
        /// Seção de detalhes do repositório
        /// </summary>
        /// <param name="filtro"> Nome do repositório a ser detalhado </param>
        /// <returns></returns>
        public ActionResult Detalhar(string filtro)
        {
            return View(GitRepositorios.TodosRepositorios().Find(a => a.name == filtro));
        }

        /// <summary>
        /// Salva se um repositório é ou não favorito
        /// </summary>
        /// <param name="nome"> nome do repositório a ser salvo</param>
        /// <param name="novoFavorito"> Se true é favorito se null não é favorito</param>
        /// <returns> Retorna para view meus repositórios </returns>
        public ActionResult SalvarFavorito(string nome, bool? novoFavorito)
        {
            if(novoFavorito == null)
            {
                novoFavorito = false;
            }

            GitRepositorios.TodosRepositorios().Find(a => a.name == nome).favorito = novoFavorito.Value;

            return View("Index",GitRepositorios.TodosRepositorios());
        }

        public ActionResult ListarFavoritos()
        {
            return View(GitRepositorios.TodosRepositorios().Where(a => a.favorito == true).ToList());

        }
    }

}

Avonale_Web/Avonale_Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1> Teste para o processo seletivo utilizando API do GitHub</h1>

Avonale_Web/Avonale_Web/Views/Repositorios/Buscar.cshtml
@model IEnumerable<Avonale_Web.Models.Repositorio>

<h2>Buscar repositórios</h2>

<div class="form-group input-group">
    <form class="navbar-form">
        <input class="form-control" name="filtro" />
        <input class="btn btn-outline-dark" type="submit" id="btn_procura" value="Filtrar" />
        <label class="radio-inline"><input type="radio" name="opcao" value="true" checked>Busca exata</label>
        <label class="radio-inline"><input type="radio" name="opcao" value="false">Busca por parte</label>
    </form>
</div>
<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.name, "Detalhar", "Repositorios", new { filtro = item.name }, null)
                        </td>
                        <td>
                            @item.description
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Avonale_Web/Avonale_Web/Views/Repositorios/Detalhar.cshtml
@model Avonale_Web.Models.Repositorio

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes do repositório</h2>
<form class="navbar-form" action="SalvarFavorito">
    <div class="container">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Favorito</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Linguagem</th>
                    <th scope="col">Última atualização</th>
                    <th scope="col">Dono</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    <tr>
                        <td>
                            @if (Model.favorito)
                            {
                                <label><input type="checkbox" value="true" checked name="novoFavorito"></label>
                            }
                            else
                            {
                                <label><input type="checkbox" value="true" name="novoFavorito"></label>
                            }
                        </td>
                        <td>
                            @Html.ActionLink(Model.name, "Detalhes", "Repositorios", new { filtro = Model.name }, null)
                        </td>
                        <td>
                            @Model.description
                        </td>
                        <td>
                            @Model.language
                        </td>
                        <td>
                            @Model.updated_at
                        </td>
                        <td>
                            @Model.owner.login
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <input type="hidden" value="@Model.name" name="nome" />
        <button type="submit" class="btn btn-success">Salvar</button>
    </div>
</form>

Avonale_Web/Avonale_Web/Views/Repositorios/Index.cshtml
@model IEnumerable<Avonale_Web.Models.Repositorio>

    <h2>Meus repositórios</h2>

    <div class="container">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Descrição</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink(item.name, "Detalhar", "Repositorios", new { filtro = item.name }, null)
                            </td>
                            <td>
                                @item.description
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

Avonale_Web/Avonale_Web/Views/Repositorios/ListarFavoritos.cshtml
@model IEnumerable<Avonale_Web.Models.Repositorio>

<h2>Meus repositórios favoritos</h2>

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.name, "Detalhar", "Repositorios", new { filtro = item.name }, null)
                        </td>
                        <td>
                            @item.description
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Avonale_Web/Avonale_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Início", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Favoritos", "ListarFavoritos", "Repositorios")</li>
                    <li>@Html.ActionLink("Meus repositórios", "Index", "Repositorios")</li>
                    <li>@Html.ActionLink("Buscar", "Buscar", "Repositorios")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aplicativo de Carlos Robson para o teste Avonale C#</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>